In [3]:
! pip install geopandas
! pip install pysal

Requirement already satisfied: geopandas in /home/kenny/miniconda3/lib/python3.6/site-packages (0.4.1)
Requirement already satisfied: shapely in /home/kenny/miniconda3/lib/python3.6/site-packages (from geopandas) (1.6.4.post1)
Requirement already satisfied: fiona in /home/kenny/miniconda3/lib/python3.6/site-packages (from geopandas) (1.8.6)
Requirement already satisfied: pandas in /home/kenny/miniconda3/lib/python3.6/site-packages (from geopandas) (0.24.2)
Requirement already satisfied: pyproj in /home/kenny/miniconda3/lib/python3.6/site-packages (from geopandas) (2.1.3)
Requirement already satisfied: attrs>=17 in /home/kenny/miniconda3/lib/python3.6/site-packages (from fiona->geopandas) (19.1.0)
Requirement already satisfied: click<8,>=4.0 in /home/kenny/miniconda3/lib/python3.6/site-packages (from fiona->geopandas) (7.0)
Requirement already satisfied: cligj>=0.5 in /home/kenny/miniconda3/lib/python3.6/site-packages (from fiona->geopandas) (0.5.0)
Requirement already satisfied: click-plugins>=1.0 in /home/kenny/miniconda3/lib/python3.6/site-packages (from fiona->geopandas) (1.1.1)
Requirement already satisfied: six>=1.7 in /home/kenny/miniconda3/lib/python3.6/site-packages (from fiona->geopandas) (1.12.0)
Requirement already satisfied: munch in /home/kenny/miniconda3/lib/python3.6/site-packages (from fiona->geopandas) (2.3.2)
Requirement already satisfied: numpy>=1.12.0 in /home/kenny/miniconda3/lib/python3.6/site-packages (from pandas->geopandas) (1.16.2)
Requirement already satisfied: pytz>=2011k in /home/kenny/miniconda3/lib/python3.6/site-packages (from pandas->geopandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/kenny/miniconda3/lib/python3.6/site-packages (from pandas->geopandas) (2.8.0)
Requirement already satisfied: pysal in /home/kenny/miniconda3/lib/python3.6/site-packages (1.14.4.post1)
Requirement already satisfied: scipy>=0.11 in /home/kenny/miniconda3/lib/python3.6/site-packages (from pysal) (1.2.1)
Requirement already satisfied: numpy>=1.3 in /home/kenny/miniconda3/lib/python3.6/site-packages (from pysal) (1.16.2)

## Import Necessary Packages

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import geopandas as gpd
import pysal as ps
import shapely.geometry
from pyproj import CRS

from pandas import DataFrame,Series

## What is Pandas?

- Pandas provides a SQL-like approach (that blends in elements of statistics and linear algebra) to analyzing tables of data
- DataFrames in R are very similar
- Pandas has been adopted as a de facto standard for input and vectorization across numerous disciplines including Python data analysis with spatial components

### Loading data from a csv

In [5]:
basedf=pd.read_csv('ss13hil.csv')
basedf[['SERIALNO', 'PUMA00', 'PUMA10', 'ST', 'ADJHSG', 'ADJINC',
        'WGTP', 'NP', 'TYPE', 'ACR', 'AGS', 'BATH', 'BDSP',
        'BLD', 'BUS', 'CONP', 'ELEP', 'FS', 'FULP']].head()

,SERIALNO,PUMA00,PUMA10,ST,ADJHSG,ADJINC,WGTP,NP,TYPE,ACR,AGS,BATH,BDSP,BLD,BUS,CONP,ELEP,FS,FULP
0,2009000000061,3515,-9,17,1086032,1085467,36,0,1,NaN,NaN,2.0,2.0,8.0,NaN,0.0,NaN,NaN,NaN
1,2009000000075,1000,-9,17,1086032,1085467,6,1,1,1.0,NaN,1.0,3.0,1.0,2.0,0.0,200.0,2.0,2.0
2,2009000000108,3402,-9,17,1086032,1085467,15,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,80.0,2.0,2.0
3,2009000000132,3510,-9,17,1086032,1085467,60,4,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,1.0,2.0,2.0
4,2009000000150,3518,-9,17,1086032,1085467,37,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,200.0,1.0,2.0

In [27]:
basedf=pd.read_csv('ss13hil.csv', index_col='SERIALNO',
                   usecols=['SERIALNO', 'PUMA00', 'PUMA10', 'ST',
                            'ADJHSG', 'ADJINC', 'WGTP', 'NP', 'TYPE', 'ACR',
                            'AGS', 'BATH', 'BDSP', 'BLD', 'BUS', 'CONP', 'ELEP',
                            'FS', 'FULP'])
basedf.head()

,PUMA00,PUMA10,ST,ADJHSG,ADJINC,WGTP,NP,TYPE,ACR,AGS,BATH,BDSP,BLD,BUS,CONP,ELEP,FS,FULP
SERIALNO,,,,,,,,,,,,,,,,,,
2009000000061,3515,-9,17,1086032,1085467,36,0,1,NaN,NaN,2.0,2.0,8.0,NaN,0.0,NaN,NaN,NaN
2009000000075,1000,-9,17,1086032,1085467,6,1,1,1.0,NaN,1.0,3.0,1.0,2.0,0.0,200.0,2.0,2.0
2009000000108,3402,-9,17,1086032,1085467,15,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,80.0,2.0,2.0
2009000000132,3510,-9,17,1086032,1085467,60,4,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,1.0,2.0,2.0
2009000000150,3518,-9,17,1086032,1085467,37,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,200.0,1.0,2.0

### query
- query takes a text string argument in the form (roughly) of a SQL WHERE clause
- Column names need to be referenced without quoting so suitable single-word names are needed
- https://pandas.pydata.org/pandas-docs/version/0.22/indexing.html#indexing-query

In [7]:
basedf.query('PUMA00==3515')

,PUMA00,PUMA10,ST,ADJHSG,ADJINC,WGTP,NP,TYPE,ACR,AGS,BATH,BDSP,BLD,BUS,CONP,ELEP,FS,FULP
SERIALNO,,,,,,,,,,,,,,,,,,
2009000000061,3515,-9,17,1086032,1085467,36,0,1,NaN,NaN,2.0,2.0,8.0,NaN,0.0,NaN,NaN,NaN
2009000002489,3515,-9,17,1086032,1085467,15,1,1,2.0,1.0,1.0,2.0,2.0,2.0,0.0,50.0,1.0,1.0
2009000002611,3515,-9,17,1086032,1085467,49,2,1,NaN,NaN,1.0,1.0,6.0,NaN,0.0,50.0,2.0,2.0
2009000002724,3515,-9,17,1086032,1085467,45,1,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,40.0,2.0,2.0
2009000006025,3515,-9,17,1086032,1085467,17,2,1,NaN,NaN,1.0,2.0,4.0,NaN,0.0,100.0,2.0,2.0
2009000009853,3515,-9,17,1086032,1085467,14,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,150.0,2.0,2.0
2009000010773,3515,-9,17,1086032,1085467,18,2,1,1.0,NaN,1.0,3.0,3.0,2.0,0.0,110.0,2.0,2.0
2009000012599,3515,-9,17,1086032,1085467,60,4,1,1.0,NaN,1.0,8.0,2.0,2.0,0.0,50.0,2.0,2.0
2009000012695,3515,-9,17,1086032,1085467,44,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,110.0,2.0,2.0
2009000013780,3515,-9,17,1086032,1085467,20,3,1,NaN,NaN,1.0,2.0,4.0,NaN,0.0,140.0,2.0,2.0
2009000021230,3515,-9,17,1086032,1085467,18,1,1,NaN,NaN,1.0,0.0,8.0,NaN,0.0,30.0,2.0,2.0
2009000022438,3515,-9,17,1086032,1085467,0,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
2009000022715,3515,-9,17,1086032,1085467,33,1,1,NaN,NaN,1.0,1.0,6.0,NaN,0.0,20.0,2.0,2.0
2009000022871,3515,-9,17,1086032,1085467,27,7,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,70.0,1.0,2.0
2009000023991,3515,-9,17,1086032,1085467,34,1,1,NaN,NaN,1.0,0.0,9.0,NaN,0.0,2.0,2.0,2.0
2009000024254,3515,-9,17,1086032,1085467,15,4,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,100.0,1.0,2.0
2009000026127,3515,-9,17,1086032,1085467,24,1,1,NaN,NaN,1.0,0.0,9.0,NaN,0.0,1.0,1.0,2.0
2009000026822,3515,-9,17,1086032,1085467,34,0,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,NaN,NaN,NaN
2009000027183,3515,-9,17,1086032,1085467,23,2,1,NaN,NaN,1.0,2.0,7.0,NaN,0.0,40.0,2.0,2.0
2009000027392,3515,-9,17,1086032,1085467,37,0,1,NaN,NaN,1.0,1.0,5.0,NaN,0.0,NaN,NaN,NaN
2009000028444,3515,-9,17,1086032,1085467,21,1,1,NaN,NaN,1.0,1.0,6.0,NaN,0.0,20.0,1.0,2.0
2009000028568,3515,-9,17,1086032,1085467,14,0,1,1.0,NaN,1.0,2.0,2.0,2.0,0.0,NaN,NaN,NaN
2009000030494,3515,-9,17,1086032,1085467,39,6,1,NaN,NaN,1.0,2.0,7.0,NaN,0.0,120.0,1.0,2.0
2009000031347,3515,-9,17,1086032,1085467,31,1,1,NaN,NaN,1.0,0.0,6.0,NaN,0.0,140.0,2.0,2.0
2009000032751,3515,-9,17,1086032,1085467,0,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
2009000032821,3515,-9,17,1086032,1085467,40,0,1,NaN,NaN,1.0,1.0,6.0,NaN,0.0,NaN,NaN,NaN
2009000039391,3515,-9,17,1086032,1085467,41,1,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,70.0,2.0,2.0
2009000039418,3515,-9,17,1086032,1085467,17,1,1,NaN,NaN,1.0,8.0,7.0,NaN,0.0,1.0,1.0,1.0
2009000042011,3515,-9,17,1086032,1085467,33,3,1,NaN,NaN,1.0,4.0,5.0,NaN,0.0,100.0,2.0,2.0
2009000046340,3515,-9,17,1086032,1085467,40,4,1,NaN,NaN,1.0,3.0,5.0,NaN,0.0,80.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011001440178,3515,-9,17,1035725,1054614,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
2011001443385,3515,-9,17,1035725,1054614,11,1,1,NaN,NaN,1.0,2.0,4.0,NaN,0.0,40.0,2.0,2.0
2011001443607,3515,-9,17,1035725,1054614,0,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
2011001451083,3515,-9,17,1035725,1054614,8,1,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,180.0,2.0,2.0
2011001451956,3515,-9,17,1035725,1054614,38,6,1,NaN,NaN,1.0,4.0,4.0,NaN,0.0,20.0,1.0,2.0
2011001452314,3515,-9,17,1035725,1054614,63,1,1,NaN,NaN,1.0,3.0,8.0,NaN,790.0,30.0,2.0,1.0
2011001452423,3515,-9,17,1035725,1054614,17,1,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,40.0,2.0,2.0
2011001455146,3515,-9,17,1035725,1054614,21,1,1,NaN,NaN,1.0,2.0,8.0,NaN,0.0,50.0,1.0,2.0
2011001455997,3515,-9,17,1035725,1054614,0,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
2011001458835,3515,-9,17,1035725,1054614,14,2,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,40.0,2.0,2.0
2011001459951,3515,-9,17,1035725,1054614,31,2,1,NaN,NaN,1.0,3.0,4.0,NaN,0.0,200.0,2.0,2.0
2011001462339,3515,-9,17,1035725,1054614,11,4,1,NaN,NaN,1.0,3.0,5.0,NaN,0.0,330.0,1.0,2.0
2011001462348,3515,-9,17,1035725,1054614,27,6,1,1.0,NaN,1.0,3.0,3.0,2.0,0.0,2.0,1.0,2.0
2011001462403,3515,-9,17,1035725,1054614,31,2,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,50.0,2.0,2.0
2011001462832,3515,-9,17,1035725,1054614,23,0,1,NaN,NaN,1.0,2.0,4.0,NaN,0.0,NaN,NaN,NaN
2011001465772,3515,-9,17,1035725,1054614,6,1,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,30.0,2.0,2.0
2011001472550,3515,-9,17,1035725,1054614,29,0,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,NaN,NaN,NaN
2011001472759,3515,-9,17,1035725,1054614,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2011001474048,3515,-9,17,1035725,1054614,19,1,1,NaN,NaN,1.0,4.0,5.0,NaN,0.0,50.0,2.0,2.0
2011001476013,3515,-9,17,1035725,1054614,27,0,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,NaN,NaN,NaN
2011001476580,3515,-9,17,1035725,1054614,25,3,1,1.0,NaN,1.0,3.0,3.0,2.0,0.0,60.0,1.0,2.0
2011001477441,3515,-9,17,1035725,1054614,21,0,1,NaN,NaN,1.0,1.0,6.0,NaN,0.0,NaN,NaN,NaN
2011001482923,3515,-9,17,1035725,1054614,17,0,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,NaN,NaN,NaN
2011001484742,3515,-9,17,1035725,1054614,23,4,1,NaN,NaN,1.0,4.0,5.0,NaN,0.0,510.0,1.0,2.0
2011001488279,3515,-9,17,1035725,1054614,21,2,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,70.0,1.0,1200.0
2011001490359,3515,-9,17,1035725,1054614,8,1,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,130.0,2.0,2.0
2011001490407,3515,-9,17,1035725,1054614,25,3,1,NaN,NaN,1.0,3.0,4.0,NaN,0.0,120.0,1.0,2.0
2011001490668,3515,-9,17,1035725,1054614,12,1,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,30.0,2.0,1.0
2011001495911,3515,-9,17,1035725,1054614,0,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN
2011001497253,3515,-9,17,1035725,1054614,9,2,1,NaN,NaN,1.0,5.0,4.0,NaN,0.0,90.0,2.0,2.0

- The query functionality can work between fields.
- However, the only operators that I would rely on are (==, !=, <, >, <=, >=, &, | )
- query() is by default evaluated using the numexpr engine, which outperforms pure python on DataFrames of more than 200,000 rows

In [8]:
basedf.query('BDSP==NP')

,PUMA00,PUMA10,ST,ADJHSG,ADJINC,WGTP,NP,TYPE,ACR,AGS,BATH,BDSP,BLD,BUS,CONP,ELEP,FS,FULP
SERIALNO,,,,,,,,,,,,,,,,,,
2009000000108,3402,-9,17,1086032,1085467,15,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,80.0,2.0,2.0
2009000000150,3518,-9,17,1086032,1085467,37,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,200.0,1.0,2.0
2009000000225,3402,-9,17,1086032,1085467,19,2,1,NaN,NaN,1.0,2.0,9.0,NaN,0.0,1.0,2.0,2.0
2009000000256,600,-9,17,1086032,1085467,26,2,1,NaN,NaN,1.0,2.0,7.0,NaN,0.0,90.0,1.0,2.0
2009000000335,2700,-9,17,1086032,1085467,28,1,1,NaN,NaN,1.0,1.0,5.0,NaN,0.0,60.0,2.0,2.0
2009000000461,400,-9,17,1086032,1085467,43,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,100.0,1.0,2.0
2009000000496,1101,-9,17,1086032,1085467,53,2,1,NaN,NaN,1.0,2.0,7.0,NaN,0.0,70.0,2.0,2.0
2009000000629,3001,-9,17,1086032,1085467,22,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,100.0,2.0,2.0
2009000000775,3510,-9,17,1086032,1085467,24,1,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,1.0,2.0,1.0
2009000000912,1800,-9,17,1086032,1085467,7,1,1,1.0,NaN,1.0,1.0,2.0,2.0,0.0,20.0,2.0,2.0
2009000001130,3005,-9,17,1086032,1085467,19,1,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,50.0,2.0,2.0
2009000001170,1000,-9,17,1086032,1085467,22,3,1,2.0,1.0,1.0,3.0,2.0,2.0,0.0,130.0,2.0,2.0
2009000001233,200,-9,17,1086032,1085467,8,1,1,1.0,NaN,1.0,1.0,2.0,2.0,0.0,510.0,2.0,1000.0
2009000001398,3305,-9,17,1086032,1085467,13,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,150.0,2.0,2.0
2009000001474,3104,-9,17,1086032,1085467,21,5,1,1.0,NaN,1.0,5.0,2.0,1.0,0.0,200.0,2.0,2.0
2009000001515,3502,-9,17,1086032,1085467,13,2,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,30.0,2.0,2.0
2009000001591,200,-9,17,1086032,1085467,2,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,150.0,2.0,2.0
2009000001736,2700,-9,17,1086032,1085467,19,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,200.0,2.0,2.0
2009000001902,3206,-9,17,1086032,1085467,17,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,70.0,2.0,2.0
2009000001950,2900,-9,17,1086032,1085467,16,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,80.0,2.0,2.0
2009000002087,500,-9,17,1086032,1085467,3,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,70.0,2.0,2.0
2009000002113,1300,-9,17,1086032,1085467,20,2,1,2.0,1.0,1.0,2.0,1.0,2.0,0.0,130.0,2.0,2.0
2009000002240,900,-9,17,1086032,1085467,24,2,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,1.0,2.0,1.0
2009000002293,3510,-9,17,1086032,1085467,23,1,1,NaN,NaN,1.0,1.0,5.0,NaN,0.0,40.0,1.0,2.0
2009000002317,3405,-9,17,1086032,1085467,12,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,150.0,2.0,2.0
2009000002429,3410,-9,17,1086032,1085467,24,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,160.0,2.0,2.0
2009000002483,3511,-9,17,1086032,1085467,13,2,1,NaN,NaN,1.0,2.0,4.0,NaN,0.0,80.0,2.0,2.0
2009000002496,3206,-9,17,1086032,1085467,17,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,100.0,2.0,2.0
2009000002722,1400,-9,17,1086032,1085467,14,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,200.0,2.0,2.0
2009000002726,3204,-9,17,1086032,1085467,20,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,80.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013001488955,-9,2000,17,1000000,1007549,20,2,1,NaN,NaN,1.0,2.0,7.0,NaN,0.0,90.0,2.0,2.0
2013001488994,-9,3521,17,1000000,1007549,15,2,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,50.0,2.0,2.0
2013001489051,-9,2501,17,1000000,1007549,4,2,1,1.0,NaN,1.0,2.0,2.0,2.0,0.0,80.0,2.0,2.0
2013001489062,-9,3007,17,1000000,1007549,41,2,1,1.0,NaN,1.0,2.0,2.0,2.0,0.0,100.0,2.0,2.0
2013001489147,-9,3420,17,1000000,1007549,77,3,1,NaN,NaN,1.0,3.0,8.0,NaN,240.0,70.0,2.0,2.0
2013001489260,-9,3502,17,1000000,1007549,11,1,1,NaN,NaN,1.0,1.0,8.0,NaN,0.0,30.0,2.0,2.0
2013001489329,-9,2100,17,1000000,1007549,5,1,1,1.0,NaN,1.0,1.0,2.0,2.0,0.0,90.0,2.0,2.0
2013001489749,-9,3102,17,1000000,1007549,41,1,1,NaN,NaN,1.0,1.0,6.0,NaN,0.0,40.0,2.0,2.0
2013001489860,-9,1300,17,1000000,1007549,64,5,1,1.0,NaN,1.0,5.0,2.0,2.0,0.0,320.0,1.0,2.0
2013001489873,-9,3205,17,1000000,1007549,49,1,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,1.0,2.0,2.0
2013001489894,-9,3204,17,1000000,1007549,27,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,80.0,2.0,2.0
2013001489972,-9,3700,17,1000000,1007549,3,2,1,1.0,NaN,1.0,2.0,1.0,2.0,0.0,90.0,1.0,2.0
2013001489989,-9,105,17,1000000,1007549,32,1,1,1.0,NaN,1.0,1.0,2.0,2.0,0.0,40.0,1.0,2.0
2013001490108,-9,3530,17,1000000,1007549,17,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,140.0,2.0,2.0
2013001490119,-9,1701,17,1000000,1007549,17,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,300.0,2.0,2.0
2013001490258,-9,300,17,1000000,1007549,13,3,1,2.0,3.0,1.0,3.0,2.0,2.0,0.0,130.0,2.0,2.0
2013001490268,-9,501,17,1000000,1007549,36,1,1,2.0,1.0,1.0,1.0,2.0,2.0,0.0,100.0,2.0,2.0
2013001490278,-9,2200,17,1000000,1007549,9,4,1,2.0,1.0,1.0,4.0,2.0,2.0,0.0,130.0,2.0,2.0
2013001490298,-9,2700,17,1000000,1007549,11,2,1,1.0,NaN,1.0,2.0,2.0,2.0,0.0,80.0,1.0,2.0
2013001490306,-9,3527,17,1000000,1007549,17,2,1,1.0,NaN,1.0,2.0,2.0,2.0,0.0,70.0,2.0,2.0
2013001490917,-9,3523,17,1000000,1007549,32,2,1,NaN,NaN,1.0,2.0,7.0,NaN,0.0,60.0,1.0,2.0
2013001490936,-9,3410,17,1000000,1007549,31,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,120.0,2.0,2.0
2013001491195,-9,3504,17,1000000,1007549,8,2,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,30.0,2.0,2.0
2013001491345,-9,202,17,1000000,1007549,14,2,1,2.0,1.0,1.0,2.0,2.0,2.0,0.0,120.0,2.0,2.0
2013001491689,-9,3602,17,1000000,1007549,19,2,1,1.0,NaN,1.0,2.0,2.0,2.0,0.0,80.0,2.0,2.0
2013001492048,-9,1300,17,1000000,1007549,7,3,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,130.0,2.0,2.0
2013001492331,-9,3209,17,1000000,1007549,11,2,1,NaN,NaN,1.0,2.0,9.0,NaN,0.0,1.0,2.0,2.0
2013001492691,-9,3418,17,1000000,1007549,45,4,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,80.0,2.0,2.0
2013001492749,-9,3102,17,1000000,1007549,19,2,1,1.0,NaN,1.0,2.0,2.0,2.0,0.0,40.0,1.0,2.0
2013001492822,-9,3530,17,1000000,1007549,15,1,1,1.0,NaN,1.0,1.0,2.0,2.0,0.0,1.0,2.0,2.0

- Arithmetic is possible although I can’t speak to its efficiency
- The use of in and not in operators as well as ==[’a’,’b’,...], although parts of this will generally be evaluated using pure python

In [10]:
basedf.query('0<BDSP<NP & PUMA00==3515')

,PUMA00,PUMA10,ST,ADJHSG,ADJINC,WGTP,NP,TYPE,ACR,AGS,BATH,BDSP,BLD,BUS,CONP,ELEP,FS,FULP
SERIALNO,,,,,,,,,,,,,,,,,,
2009000002611,3515,-9,17,1086032,1085467,49,2,1,NaN,NaN,1.0,1.0,6.0,NaN,0.0,50.0,2.0,2.0
2009000013780,3515,-9,17,1086032,1085467,20,3,1,NaN,NaN,1.0,2.0,4.0,NaN,0.0,140.0,2.0,2.0
2009000022871,3515,-9,17,1086032,1085467,27,7,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,70.0,1.0,2.0
2009000024254,3515,-9,17,1086032,1085467,15,4,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,100.0,1.0,2.0
2009000030494,3515,-9,17,1086032,1085467,39,6,1,NaN,NaN,1.0,2.0,7.0,NaN,0.0,120.0,1.0,2.0
2009000046340,3515,-9,17,1086032,1085467,40,4,1,NaN,NaN,1.0,3.0,5.0,NaN,0.0,80.0,1.0,2.0
2009000069632,3515,-9,17,1086032,1085467,30,4,1,NaN,NaN,1.0,3.0,4.0,NaN,0.0,80.0,2.0,2.0
2009000086634,3515,-9,17,1086032,1085467,15,4,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,80.0,1.0,2.0
2009000088409,3515,-9,17,1086032,1085467,40,5,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,70.0,1.0,2.0
2009000124024,3515,-9,17,1086032,1085467,25,5,1,1.0,NaN,1.0,2.0,3.0,2.0,0.0,80.0,2.0,2.0
2009000134542,3515,-9,17,1086032,1085467,37,6,1,1.0,NaN,1.0,5.0,2.0,2.0,0.0,230.0,1.0,2.0
2009000135687,3515,-9,17,1086032,1085467,31,5,1,NaN,NaN,1.0,2.0,9.0,NaN,0.0,30.0,2.0,2.0
2009000137681,3515,-9,17,1086032,1085467,40,5,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,240.0,1.0,2.0
2009000143272,3515,-9,17,1086032,1085467,55,3,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,40.0,1.0,2.0
2009000164550,3515,-9,17,1086032,1085467,42,3,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,30.0,1.0,2.0
2009000235371,3515,-9,17,1086032,1085467,22,4,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,50.0,1.0,50.0
2009000242105,3515,-9,17,1086032,1085467,30,4,1,NaN,NaN,1.0,3.0,5.0,NaN,0.0,250.0,2.0,2.0
2009000261112,3515,-9,17,1086032,1085467,48,4,1,NaN,NaN,1.0,2.0,4.0,NaN,0.0,150.0,2.0,2.0
2009000278006,3515,-9,17,1086032,1085467,15,4,1,NaN,NaN,1.0,2.0,8.0,NaN,0.0,10.0,1.0,2.0
2009000281193,3515,-9,17,1086032,1085467,23,13,1,1.0,NaN,1.0,8.0,2.0,2.0,0.0,200.0,1.0,2.0
2009000289745,3515,-9,17,1086032,1085467,71,3,1,NaN,NaN,1.0,2.0,8.0,NaN,0.0,70.0,1.0,2.0
2009000290319,3515,-9,17,1086032,1085467,30,3,1,NaN,NaN,1.0,2.0,7.0,NaN,0.0,20.0,1.0,2.0
2009000298561,3515,-9,17,1086032,1085467,16,4,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,50.0,2.0,3700.0
2009000302575,3515,-9,17,1086032,1085467,18,3,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,150.0,1.0,2.0
2009000304973,3515,-9,17,1086032,1085467,18,6,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,180.0,2.0,2.0
2009000310241,3515,-9,17,1086032,1085467,49,3,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,80.0,2.0,2.0
2009000320632,3515,-9,17,1086032,1085467,30,5,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,90.0,1.0,2.0
2009000343682,3515,-9,17,1086032,1085467,17,3,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,70.0,2.0,2.0
2009000345878,3515,-9,17,1086032,1085467,16,5,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,150.0,1.0,2.0
2009000347349,3515,-9,17,1086032,1085467,10,3,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,150.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011001168857,3515,-9,17,1035725,1054614,20,2,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,50.0,2.0,1.0
2011001169212,3515,-9,17,1035725,1054614,21,4,1,NaN,NaN,2.0,2.0,4.0,NaN,0.0,230.0,2.0,2.0
2011001176565,3515,-9,17,1035725,1054614,19,3,1,NaN,NaN,1.0,1.0,5.0,NaN,0.0,230.0,2.0,2.0
2011001205856,3515,-9,17,1035725,1054614,15,7,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,170.0,1.0,2.0
2011001218196,3515,-9,17,1035725,1054614,20,3,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,190.0,2.0,2.0
2011001218409,3515,-9,17,1035725,1054614,15,3,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,130.0,2.0,2.0
2011001234936,3515,-9,17,1035725,1054614,25,7,1,1.0,NaN,1.0,4.0,2.0,2.0,0.0,140.0,2.0,2.0
2011001237682,3515,-9,17,1035725,1054614,24,7,1,NaN,NaN,2.0,2.0,5.0,NaN,0.0,60.0,1.0,2.0
2011001245795,3515,-9,17,1035725,1054614,20,3,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,50.0,1.0,2.0
2011001249889,3515,-9,17,1035725,1054614,47,3,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,100.0,1.0,2.0
2011001253824,3515,-9,17,1035725,1054614,8,3,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,90.0,1.0,2.0
2011001267924,3515,-9,17,1035725,1054614,28,3,1,1.0,NaN,1.0,2.0,2.0,2.0,0.0,100.0,2.0,2.0
2011001270004,3515,-9,17,1035725,1054614,8,2,1,NaN,NaN,1.0,1.0,8.0,NaN,0.0,120.0,1.0,2.0
2011001273174,3515,-9,17,1035725,1054614,18,4,1,NaN,NaN,1.0,2.0,5.0,NaN,0.0,90.0,2.0,2.0
2011001275567,3515,-9,17,1035725,1054614,19,7,1,1.0,NaN,1.0,5.0,2.0,2.0,0.0,230.0,1.0,2.0
2011001282747,3515,-9,17,1035725,1054614,8,3,1,NaN,NaN,1.0,2.0,4.0,NaN,0.0,170.0,1.0,1.0
2011001314614,3515,-9,17,1035725,1054614,16,2,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,80.0,1.0,2.0
2011001346410,3515,-9,17,1035725,1054614,21,3,1,NaN,NaN,1.0,2.0,6.0,NaN,0.0,200.0,2.0,2.0
2011001354034,3515,-9,17,1035725,1054614,9,4,1,NaN,NaN,1.0,3.0,6.0,NaN,0.0,60.0,1.0,2.0
2011001357889,3515,-9,17,1035725,1054614,10,2,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,1.0,2.0,1.0
2011001367548,3515,-9,17,1035725,1054614,13,4,1,NaN,NaN,1.0,3.0,6.0,NaN,0.0,150.0,1.0,2.0
2011001369426,3515,-9,17,1035725,1054614,14,3,1,NaN,NaN,1.0,2.0,4.0,NaN,0.0,150.0,2.0,2.0
2011001373719,3515,-9,17,1035725,1054614,70,4,1,1.0,NaN,1.0,3.0,2.0,2.0,0.0,330.0,2.0,2.0
2011001386614,3515,-9,17,1035725,1054614,28,3,1,1.0,NaN,1.0,2.0,2.0,2.0,0.0,100.0,2.0,2.0
2011001388819,3515,-9,17,1035725,1054614,14,5,1,NaN,NaN,1.0,3.0,5.0,NaN,0.0,160.0,2.0,2.0
2011001431836,3515,-9,17,1035725,1054614,12,3,1,NaN,NaN,1.0,2.0,9.0,NaN,0.0,130.0,1.0,2.0
2011001451956,3515,-9,17,1035725,1054614,38,6,1,NaN,NaN,1.0,4.0,4.0,NaN,0.0,20.0,1.0,2.0
2011001458835,3515,-9,17,1035725,1054614,14,2,1,NaN,NaN,1.0,1.0,9.0,NaN,0.0,40.0,2.0,2.0
2011001462339,3515,-9,17,1035725,1054614,11,4,1,NaN,NaN,1.0,3.0,5.0,NaN,0.0,330.0,1.0,2.0
2011001462348,3515,-9,17,1035725,1054614,27,6,1,1.0,NaN,1.0,3.0,3.0,2.0,0.0,2.0,1.0,2.0

### concat as JOIN
- If the indexes are overlapping and the column names are not the same and axis=1 is used, that is identical to that of INNER JOIN from SQL

In [13]:
df1=DataFrame({'a':[1,2,3], 'b':[4,5,6]}, index=['x','y','z'])
df2=DataFrame({'c':[7,8,9], 'd':[10,11,12]}, index=['x','y','z'])
pd.concat([df1,df2],axis=1)

   a  b  c   d
x  1  4  7  10
y  2  5  8  11
z  3  6  9  12

### merge as JOIN
- merge is a holistic JOIN operator
- Like SQL JOINs, the options for using it are complex and take a great deal of practice to master
- We will focus on two options: on= and how=
- on determines the common column used to join the two together (a list of common columns can be specified)
- note that the indexes are not preserved. To keep them .reset index() before joining and then set the index from that column after or join on index (not covered here)

In [14]:
df1=DataFrame({'a':[1,2,3], 'b':[4,5,6]}, index=['x','y','z'])
df2=DataFrame({'a':[1,2,3], 'c':[10,11,12]}, index=['u','v','w'])
pd.merge(df1,df2,on='a')

   a  b   c
0  1  4  10
1  2  5  11
2  3  6  12

### merge as INNER JOIN
- how can be set to left, right, inner, or outer
- The left on and right on options specify the matching columns on the left and right join tables if they have different names
- Note that the default value of how is inner and this will filter out non-matching rows symmetrically

In [15]:
df1=DataFrame({'a1':[1,2,3], 'b':[4,5,6]})
df2=DataFrame({'a2':[1,2,7], 'c':[10,11,12]})
pd.merge(df1,df2,how='inner',left_on='a1',right_on='a2')

   a1  b  a2   c
0   1  4   1  10
1   2  5   2  11

### merge as multi-key JOIN
- By passing a list to each of the on options, the corresponding keys are matched sequentially
- In this case two rows are found to match if and only if the value of a1 matches a2 and key1 matches key2

In [16]:
df1=DataFrame({'a1':[1,2,3],'key1':['R','R','C'] ,'b':[4,5,6]})
df2=DataFrame({'a2':[1,2,7],'key2':['R','D','C'], 'c':[10,11,12]})
pd.merge(df1,df2,how='outer',left_on=['a1','key1'],right_on=['a2','key2'])

    a1 key1    b   a2 key2     c
0  1.0    R  4.0  1.0    R  10.0
1  2.0    R  5.0  NaN  NaN   NaN
2  3.0    C  6.0  NaN  NaN   NaN
3  NaN  NaN  NaN  2.0    D  11.0
4  NaN  NaN  NaN  7.0    C  12.0

### map as Transforming Columns
- .map(f) applies to a Series
- It iterates efficiently over every element of the series and applies the function f to that element
- Then it assembles a new Series comprised of the transformed elements in the same order with the same index and returns it
- Weak implicit typing is critical here

In [21]:
basedf['NP\_sq']=basedf['NP'].map(lambda x: x**2)
basedf['PUMA\_str']=basedf['PUMA00'].map(lambda x: 'PUMA:'+str(x))

### Split-Apply-Combine as an overall strategy
- Similar to (but more general than) GROUP BY in SQL
- General tool for bulk changes
- The splitting step breaks data into groups using any column (including the row number)
- This can be accomplished using df.groupby('year')

### Split-Apply-Combine in more detail
- Groups produced by the split can be individually transformed by an arbitrary function
- This is the essence of Apply (the DataFrame extension of Map)
- The result is combined back into a single DataFrame

In [35]:
subdf = basedf.query('PUMA00 == 3515').copy()

def computeWeightedNP(x):
    x['weightedNP'] = x['NP']*x['WGTP']
    return x

subdf = subdf.apply(computeWeightedNP, axis=1)
totals = subdf.sum()
totals['weightedNP'] / totals['WGTP']

1.707378252712293

### apply as CROSS APPLY

In [38]:
def computeWeightedNP(x):
    x['weightedNP'] = x['NP'] * x['WGTP']
    #print(x)
    totals = x.sum()
    x['avgNP'] = totals['weightedNP'] / totals['WGTP']
    return x

subdf.groupby(['PUMA00']).apply(computeWeightedNP)

,PUMA00,PUMA10,ST,ADJHSG,ADJINC,WGTP,NP,TYPE,ACR,AGS,BATH,BDSP,BLD,BUS,CONP,ELEP,FS,FULP,weightedNP,avgNP
SERIALNO,,,,,,,,,,,,,,,,,,,,
2009000000061,3515.0,-9.0,17.0,1086032.0,1085467.0,36.0,0.0,1.0,NaN,NaN,2.0,2.0,8.0,NaN,0.0,NaN,NaN,NaN,0.0,1.707378
2009000002489,3515.0,-9.0,17.0,1086032.0,1085467.0,15.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,0.0,50.0,1.0,1.0,15.0,1.707378
2009000002611,3515.0,-9.0,17.0,1086032.0,1085467.0,49.0,2.0,1.0,NaN,NaN,1.0,1.0,6.0,NaN,0.0,50.0,2.0,2.0,98.0,1.707378
2009000002724,3515.0,-9.0,17.0,1086032.0,1085467.0,45.0,1.0,1.0,1.0,NaN,1.0,3.0,2.0,2.0,0.0,40.0,2.0,2.0,45.0,1.707378
2009000006025,3515.0,-9.0,17.0,1086032.0,1085467.0,17.0,2.0,1.0,NaN,NaN,1.0,2.0,4.0,NaN,0.0,100.0,2.0,2.0,34.0,1.707378
2009000009853,3515.0,-9.0,17.0,1086032.0,1085467.0,14.0,4.0,1.0,1.0,NaN,1.0,4.0,2.0,2.0,0.0,150.0,2.0,2.0,56.0,1.707378
2009000010773,3515.0,-9.0,17.0,1086032.0,1085467.0,18.0,2.0,1.0,1.0,NaN,1.0,3.0,3.0,2.0,0.0,110.0,2.0,2.0,36.0,1.707378
2009000012599,3515.0,-9.0,17.0,1086032.0,1085467.0,60.0,4.0,1.0,1.0,NaN,1.0,8.0,2.0,2.0,0.0,50.0,2.0,2.0,240.0,1.707378
2009000012695,3515.0,-9.0,17.0,1086032.0,1085467.0,44.0,3.0,1.0,1.0,NaN,1.0,3.0,2.0,2.0,0.0,110.0,2.0,2.0,132.0,1.707378
2009000013780,3515.0,-9.0,17.0,1086032.0,1085467.0,20.0,3.0,1.0,NaN,NaN,1.0,2.0,4.0,NaN,0.0,140.0,2.0,2.0,60.0,1.707378
2009000021230,3515.0,-9.0,17.0,1086032.0,1085467.0,18.0,1.0,1.0,NaN,NaN,1.0,0.0,8.0,NaN,0.0,30.0,2.0,2.0,18.0,1.707378
2009000022438,3515.0,-9.0,17.0,1086032.0,1085467.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,1.707378
2009000022715,3515.0,-9.0,17.0,1086032.0,1085467.0,33.0,1.0,1.0,NaN,NaN,1.0,1.0,6.0,NaN,0.0,20.0,2.0,2.0,33.0,1.707378
2009000022871,3515.0,-9.0,17.0,1086032.0,1085467.0,27.0,7.0,1.0,1.0,NaN,1.0,4.0,2.0,2.0,0.0,70.0,1.0,2.0,189.0,1.707378
2009000023991,3515.0,-9.0,17.0,1086032.0,1085467.0,34.0,1.0,1.0,NaN,NaN,1.0,0.0,9.0,NaN,0.0,2.0,2.0,2.0,34.0,1.707378
2009000024254,3515.0,-9.0,17.0,1086032.0,1085467.0,15.0,4.0,1.0,NaN,NaN,1.0,2.0,5.0,NaN,0.0,100.0,1.0,2.0,60.0,1.707378
2009000026127,3515.0,-9.0,17.0,1086032.0,1085467.0,24.0,1.0,1.0,NaN,NaN,1.0,0.0,9.0,NaN,0.0,1.0,1.0,2.0,24.0,1.707378
2009000026822,3515.0,-9.0,17.0,1086032.0,1085467.0,34.0,0.0,1.0,NaN,NaN,1.0,2.0,5.0,NaN,0.0,NaN,NaN,NaN,0.0,1.707378
2009000027183,3515.0,-9.0,17.0,1086032.0,1085467.0,23.0,2.0,1.0,NaN,NaN,1.0,2.0,7.0,NaN,0.0,40.0,2.0,2.0,46.0,1.707378
2009000027392,3515.0,-9.0,17.0,1086032.0,1085467.0,37.0,0.0,1.0,NaN,NaN,1.0,1.0,5.0,NaN,0.0,NaN,NaN,NaN,0.0,1.707378
2009000028444,3515.0,-9.0,17.0,1086032.0,1085467.0,21.0,1.0,1.0,NaN,NaN,1.0,1.0,6.0,NaN,0.0,20.0,1.0,2.0,21.0,1.707378
2009000028568,3515.0,-9.0,17.0,1086032.0,1085467.0,14.0,0.0,1.0,1.0,NaN,1.0,2.0,2.0,2.0,0.0,NaN,NaN,NaN,0.0,1.707378
2009000030494,3515.0,-9.0,17.0,1086032.0,1085467.0,39.0,6.0,1.0,NaN,NaN,1.0,2.0,7.0,NaN,0.0,120.0,1.0,2.0,234.0,1.707378
2009000031347,3515.0,-9.0,17.0,1086032.0,1085467.0,31.0,1.0,1.0,NaN,NaN,1.0,0.0,6.0,NaN,0.0,140.0,2.0,2.0,31.0,1.707378
2009000032751,3515.0,-9.0,17.0,1086032.0,1085467.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,1.707378
2009000032821,3515.0,-9.0,17.0,1086032.0,1085467.0,40.0,0.0,1.0,NaN,NaN,1.0,1.0,6.0,NaN,0.0,NaN,NaN,NaN,0.0,1.707378
2009000039391,3515.0,-9.0,17.0,1086032.0,1085467.0,41.0,1.0,1.0,NaN,NaN,1.0,2.0,6.0,NaN,0.0,70.0,2.0,2.0,41.0,1.707378
2009000039418,3515.0,-9.0,17.0,1086032.0,1085467.0,17.0,1.0,1.0,NaN,NaN,1.0,8.0,7.0,NaN,0.0,1.0,1.0,1.0,17.0,1.707378
2009000042011,3515.0,-9.0,17.0,1086032.0,1085467.0,33.0,3.0,1.0,NaN,NaN,1.0,4.0,5.0,NaN,0.0,100.0,2.0,2.0,99.0,1.707378
2009000046340,3515.0,-9.0,17.0,1086032.0,1085467.0,40.0,4.0,1.0,NaN,NaN,1.0,3.0,5.0,NaN,0.0,80.0,1.0,2.0,160.0,1.707378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011001440178,3515.0,-9.0,17.0,1035725.0,1054614.0,0.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,1.707378
2011001443385,3515.0,-9.0,17.0,1035725.0,1054614.0,11.0,1.0,1.0,NaN,NaN,1.0,2.0,4.0,NaN,0.0,40.0,2.0,2.0,11.0,1.707378
2011001443607,3515.0,-9.0,17.0,1035725.0,1054614.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,1.707378
2011001451083,3515.0,-9.0,17.0,1035725.0,1054614.0,8.0,1.0,1.0,1.0,NaN,1.0,4.0,2.0,2.0,0.0,180.0,2.0,2.0,8.0,1.707378
2011001451956,3515.0,-9.0,17.0,1035725.0,1054614.0,38.0,6.0,1.0,NaN,NaN,1.0,4.0,4.0,NaN,0.0,20.0,1.0,2.0,228.0,1.707378
2011001452314,3515.0,-9.0,17.0,1035725.0,1054614.0,63.0,1.0,1.0,NaN,NaN,1.0,3.0,8.0,NaN,790.0,30.0,2.0,1.0,63.0,1.707378
2011001452423,3515.0,-9.0,17.0,1035725.0,1054614.0,17.0,1.0,1.0,NaN,NaN,1.0,1.0,9.0,NaN,0.0,40.0,2.0,2.0,17.0,1.707378
2011001455146,3515.0,-9.0,17.0,1035725.0,1054614.0,21.0,1.0,1.0,NaN,NaN,1.0,2.0,8.0,NaN,0.0,50.0,1.0,2.0,21.0,1.707378
2011001455997,3515.0,-9.0,17.0,1035725.0,1054614.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,1.707378
2011001458835,3515.0,-9.0,17.0,1035725.0,1054614.0,14.0,2.0,1.0,NaN,NaN,1.0,1.0,9.0,NaN,0.0,40.0,2.0,2.0,28.0,1.707378
2011001459951,3515.0,-9.0,17.0,1035725.0,1054614.0,31.0,2.0,1.0,NaN,NaN,1.0,3.0,4.0,NaN,0.0,200.0,2.0,2.0,62.0,1.707378
2011001462339,3515.0,-9.0,17.0,1035725.0,1054614.0,11.0,4.0,1.0,NaN,NaN,1.0,3.0,5.0,NaN,0.0,330.0,1.0,2.0,44.0,1.707378
2011001462348,3515.0,-9.0,17.0,1035725.0,1054614.0,27.0,6.0,1.0,1.0,NaN,1.0,3.0,3.0,2.0,0.0,2.0,1.0,2.0,162.0,1.707378
2011001462403,3515.0,-9.0,17.0,1035725.0,1054614.0,31.0,2.0,1.0,1.0,NaN,1.0,3.0,2.0,2.0,0.0,50.0,2.0,2.0,62.0,1.707378
2011001462832,3515.0,-9.0,17.0,1035725.0,1054614.0,23.0,0.0,1.0,NaN,NaN,1.0,2.0,4.0,NaN,0.0,NaN,NaN,NaN,0.0,1.707378
2011001465772,3515.0,-9.0,17.0,1035725.0,1054614.0,6.0,1.0,1.0,NaN,NaN,1.0,1.0,9.0,NaN,0.0,30.0,2.0,2.0,6.0,1.707378
2011001472550,3515.0,-9.0,17.0,1035725.0,1054614.0,29.0,0.0,1.0,NaN,NaN,1.0,2.0,6.0,NaN,0.0,NaN,NaN,NaN,0.0,1.707378
2011001472759,3515.0,-9.0,17.0,1035725.0,1054614.0,0.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,1.707378
2011001474048,3515.0,-9.0,17.0,1035725.0,1054614.0,19.0,1.0,1.0,NaN,NaN,1.0,4.0,5.0,NaN,0.0,50.0,2.0,2.0,19.0,1.707378
2011001476013,3515.0,-9.0,17.0,1035725.0,1054614.0,27.0,0.0,1.0,1.0,NaN,1.0,4.0,2.0,2.0,0.0,NaN,NaN,NaN,0.0,1.707378
2011001476580,3515.0,-9.0,17.0,1035725.0,1054614.0,25.0,3.0,1.0,1.0,NaN,1.0,3.0,3.0,2.0,0.0,60.0,1.0,2.0,75.0,1.707378
2011001477441,3515.0,-9.0,17.0,1035725.0,1054614.0,21.0,0.0,1.0,NaN,NaN,1.0,1.0,6.0,NaN,0.0,NaN,NaN,NaN,0.0,1.707378
2011001482923,3515.0,-9.0,17.0,1035725.0,1054614.0,17.0,0.0,1.0,1.0,NaN,1.0,3.0,2.0,2.0,0.0,NaN,NaN,NaN,0.0,1.707378
2011001484742,3515.0,-9.0,17.0,1035725.0,1054614.0,23.0,4.0,1.0,NaN,NaN,1.0,4.0,5.0,NaN,0.0,510.0,1.0,2.0,92.0,1.707378
2011001488279,3515.0,-9.0,17.0,1035725.0,1054614.0,21.0,2.0,1.0,1.0,NaN,1.0,4.0,2.0,2.0,0.0,70.0,1.0,1200.0,42.0,1.707378
2011001490359,3515.0,-9.0,17.0,1035725.0,1054614.0,8.0,1.0,1.0,1.0,NaN,1.0,4.0,2.0,2.0,0.0,130.0,2.0,2.0,8.0,1.707378
2011001490407,3515.0,-9.0,17.0,1035725.0,1054614.0,25.0,3.0,1.0,NaN,NaN,1.0,3.0,4.0,NaN,0.0,120.0,1.0,2.0,75.0,1.707378
2011001490668,3515.0,-9.0,17.0,1035725.0,1054614.0,12.0,1.0,1.0,NaN,NaN,1.0,2.0,6.0,NaN,0.0,30.0,2.0,1.0,12.0,1.707378
2011001495911,3515.0,-9.0,17.0,1035725.0,1054614.0,0.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0.0,1.707378
2011001497253,3515.0,-9.0,17.0,1035725.0,1054614.0,9.0,2.0,1.0,NaN,NaN,1.0,5.0,4.0,NaN,0.0,90.0,2.0,2.0,18.0,1.707378

### Problems 1

1) Start from an import of the PUMS csv using the columns 'SERIALNO', 'PUMA', 'BDSP', and 'NP' (with SERIALNO as the index and a DataType of str for the PUMA column using the dtype option). load this to a variable named basedf

In [98]:
basedf = pd.read_csv('psam_h17.csv', index_col='SERIALNO',
                     usecols=['SERIALNO', 'PUMA', 'NP', 'BDSP'])
basedf.head()

               PUMA  NP  BDSP
SERIALNO
2013000000033  1300   3   3.0
2013000000037   800   1   3.0
2013000000051   105   0   1.0
2013000000079   300   1   4.0
2013000000095  1104   4   3.0

2) Use the command basedf[['PUMA']].drop duplicates() to produce a list of the unique PUMA regions.

In [99]:
unique_df = basedf[['PUMA']].drop_duplicates()
print(len(basedf))
print(len(unique_df))
print(unique_df)

292928
88
               PUMA
SERIALNO
2013000000033  1300
2013000000037   800
2013000000051   105
2013000000079   300
2013000000095  1104
2013000000163  3102
2013000000174   700
2013000000187  3530
2013000000196  3410
2013000000207  3414
2013000000238  1900
2013000000239  3407
2013000000244  1001
2013000000251  3309
2013000000258  3521
2013000000264  2901
2013000000348  3502
2013000000349  1701
2013000000359   900
2013000000382  1204
2013000000397  3007
2013000000482  3501
2013000000517  3417
2013000000547  3413
2013000000566  3526
2013000000727  3522
2013000000996  3409
2013000001078  1205
2013000001091  3106
2013000001095  3532
...             ...
2013000003365  3525
2013000003440  2601
2013000003504  2000
2013000003590  3529
2013000003643  3412
2013000003720  3527
2013000003748  3523
2013000003797   600
2013000003895  3105
2013000003971  1500
2013000004051  2700
2013000004550  3602
2013000004738  2801
2013000004810  3005
2013000005206  3205
2013000005281  3601
2013000005497  3203
2013000005627  3416
2013000006144  3107
2013000006182  3401
2013000006326   104
2013000007353  1105
2013000008967  3009
2013000009595  3207
2013000009723  3202
2013000010063  3108
2013000010641  3008
2013000012687  3408
2013000015803  3531
2013000015982  3209

[88 rows x 1 columns]

3) Using the query command, select only those rows where the PUMA region number matches one specific one that you chose to work with from the previous step. How many records are returned? (look below the readout of sample rows to see a number) Repeat this for 4 different PUMAs and compare the counts returned for each. (what is the total?) Can you rewrite this as a single query using the OR operator? make sure the resulting counts agree.

In [102]:
count_3515 = len(basedf.query('PUMA == 1300'))
count_3003 = len(basedf.query('PUMA == 800'))
count_1400 = len(basedf.query('PUMA == 3102'))
count_3502 = len(basedf.query('PUMA == 3502'))
print(count_3515)
print(count_3003)
print(count_1400)
print(count_3502)

count_sum = count_3515 + count_3003 + count_1400 + count_3502
print(count_sum)

5200
5653
2821
4633
18307

In [105]:
PUMA_check = 'PUMA == 1300 | PUMA == 800 | PUMA == 3102 | PUMA == 3502'
# combined_query = basedf.query(PUMA00_check)
# print(len(combined_query))

NP_check = 'NP > 4'

combined_check = "(" + PUMA_check + ") & " + NP_check
# print(combined_check)

combined_query = basedf.query(combined_check)
# print(combined_query)
print(len(combined_query))
combined_query.head()

959

               PUMA  NP  BDSP
SERIALNO
2013000001418  3102   5   5.0
2013000002506  3102   5   3.0
2013000014713   800   5   1.0
2013000015250   800   5   3.0
2013000020031  1300   5   4.0

In [106]:
def PUMA_filt(x):
    if x in [1300, 800, 3102, 3502]:
        return True
    else:
        return False  
    
def NP_filt(x):
    if x > 4:
        return True
    else:
        return False
        
combined_mask = (basedf['NP'].map(NP_filt)) & (basedf['PUMA'].map(PUMA_filt))
combined_masked = basedf[combined_mask]
print(len(combined_masked))

combined_query.head()

959

               PUMA  NP  BDSP
SERIALNO
2013000001418  3102   5   5.0
2013000002506  3102   5   3.0
2013000014713   800   5   1.0
2013000015250   800   5   3.0
2013000020031  1300   5   4.0

### Problems 2

1) Select off two subsets of the data using queries that on PUMAs. The first should include 01300, 00800, and 00105. The second should include 00105, 00300, 01104.

In [107]:
PUMA_check1 = 'PUMA == 1300 | PUMA == 800 | PUMA == 105'
PUMA_check2 = 'PUMA == 105 | PUMA == 300 | PUMA == 1104'

PUMA_set1 = basedf.query(PUMA_check1)
PUMA_set2 = basedf.query(PUMA_check2)

# PUMA00_set1[['PUMA00']].drop_duplicates().head()

# PUMA00_set2[['PUMA00']].drop_duplicates().head()

# basedf.query("PUMA00==1104")

2) Use merge to perform and inner join between the two tables on SERIALNO (HINT use reset index() on each first to make the old index a column in each table)

In [108]:
PUMA_set1 = PUMA_set1.reset_index()
PUMA_set2 = PUMA_set2.reset_index()

In [110]:
PUMA_set1.head()

pd.merge(PUMA_set1, PUMA_set2, on='SERIALNO')

           SERIALNO  PUMA_x  NP_x  BDSP_x  PUMA_y  NP_y  BDSP_y
0     2013000000051     105     0     1.0     105     0     1.0
1     2013000000175     105     1     3.0     105     1     3.0
2     2013000002431     105     1     2.0     105     1     2.0
3     2013000002854     105     7     9.0     105     7     9.0
4     2013000004409     105     2     3.0     105     2     3.0
5     2013000005563     105     1     1.0     105     1     1.0
6     2013000007495     105     1     1.0     105     1     1.0
7     2013000008635     105     1     3.0     105     1     3.0
8     2013000010068     105     1     1.0     105     1     1.0
9     2013000010527     105     2     2.0     105     2     2.0
10    2013000011881     105     1     NaN     105     1     NaN
11    2013000013696     105     2     2.0     105     2     2.0
12    2013000014177     105     2     3.0     105     2     3.0
13    2013000015644     105     2     3.0     105     2     3.0
14    2013000017719     105     1     0.0     105     1     0.0
15    2013000019989     105     2     2.0     105     2     2.0
16    2013000020604     105     1     2.0     105     1     2.0
17    2013000023410     105     2     2.0     105     2     2.0
18    2013000023853     105     2     3.0     105     2     3.0
19    2013000023872     105     3     9.0     105     3     9.0
20    2013000024856     105     2     4.0     105     2     4.0
21    2013000025590     105     2     3.0     105     2     3.0
22    2013000025803     105     8     3.0     105     8     3.0
23    2013000036411     105     2     4.0     105     2     4.0
24    2013000038366     105     1     NaN     105     1     NaN
25    2013000038457     105     2     3.0     105     2     3.0
26    2013000038480     105     2     4.0     105     2     4.0
27    2013000044774     105     1     2.0     105     1     2.0
28    2013000047000     105     1     3.0     105     1     3.0
29    2013000049008     105     1     1.0     105     1     1.0
...             ...     ...   ...     ...     ...   ...     ...
3904  2017001488553     105     1     NaN     105     1     NaN
3905  2017001491804     105     1     NaN     105     1     NaN
3906  2017001493533     105     1     NaN     105     1     NaN
3907  2017001496838     105     1     NaN     105     1     NaN
3908  2017001497668     105     1     NaN     105     1     NaN
3909  2017001497782     105     1     NaN     105     1     NaN
3910  2017001498242     105     1     NaN     105     1     NaN
3911  2017001498746     105     1     NaN     105     1     NaN
3912  2017001500114     105     1     NaN     105     1     NaN
3913  2017001500992     105     1     NaN     105     1     NaN
3914  2017001502002     105     1     NaN     105     1     NaN
3915  2017001502980     105     1     NaN     105     1     NaN
3916  2017001503716     105     1     NaN     105     1     NaN
3917  2017001505754     105     1     NaN     105     1     NaN
3918  2017001512737     105     1     NaN     105     1     NaN
3919  2017001515492     105     1     NaN     105     1     NaN
3920  2017001515742     105     1     NaN     105     1     NaN
3921  2017001517961     105     1     NaN     105     1     NaN
3922  2017001518627     105     1     NaN     105     1     NaN
3923  2017001519327     105     1     NaN     105     1     NaN
3924  2017001520820     105     1     NaN     105     1     NaN
3925  2017001521173     105     1     NaN     105     1     NaN
3926  2017001527521     105     1     NaN     105     1     NaN
3927  2017001529533     105     1     NaN     105     1     NaN
3928  2017001529622     105     1     NaN     105     1     NaN
3929  2017001530617     105     1     NaN     105     1     NaN
3930  2017001532343     105     1     NaN     105     1     NaN
3931  2017001534087     105     1     NaN     105     1     NaN
3932  2017001534807     105     1     NaN     105     1     NaN
3933  2017001536038     105     1     NaN     105     1     NaN

[3934 rows x 7 columns]

3) The resulting table will only have rows that appeared in both. Which PUMAs belong to the overlap?

PUMA == 105 were the rows that overlapped

### Problems 3

1) Write a map operation that scales NP as an exponent using the numpy function np.exp

2) Write a variation on the CROSS APPLY above without using apply

In [114]:
housingdf = pd.read_csv('psam_h17.csv', dtype={'PUMA':str})
basedf = pd.read_csv('psam_h17.csv', 
                      usecols=['SERIALNO', 'PUMA', 'ST',
                               'ADJHSG', 'ADJINC', 'WGTP', 'NP', 'TYPE', 'ACR',
                               'AGS', 'BATH', 'BDSP', 'BLD', 'BUS', 'CONP', 'ELEP',
                               'FS', 'FULP'])

In [117]:
housingdf['weightedNP'] = basedf['WGTP'] * basedf['NP']
g = housingdf.groupby(['PUMA'])
pumaAvgNPArray = g['weightedNP'].sum() / g['WGTP'].sum()
avgNPdf = pd.DataFrame(pumaAvgNPArray, columns=['avgNP']).reset_index()
avgNPdf.head()

    PUMA     avgNP
0  00104  1.940075
1  00105  2.064938
2  00202  1.973556
3  00300  1.985774
4  00401  2.026103

## What is in a GeoDataBase
- A GeoDB has three essential components:
    - Spatial features (with a Datum and Projection information)
    - Attributes linked to spatial features
    - A means of transforming and linking by attribute data or spatial feature
- Pandas gives us a way of managing structured attribute data, what do we need to add in order to build a usable spatial analysis data structure

## PySAL for computational geometry
- PySAL provides a high level interface for shape objects and their transformation: pysal.lib.cg
- By using PySAL objects, we can read in and handle shape files (one of the typical formats for spatial data)
- We will examine some of the functionality that PySAL grants us in the context of an object column in a standard Pandas DataFrame
- note that PySAL is also an interface to a wide range of spatial statistical models and spatial econometric models that are not accessible from other python libraries

### Loeading our Pandas Data and our Shape File
- We can begin by loading a standard DataFrame from the csv data that we are interested in
- Note how we have handled the PUMA column
- Then we can load the shape file separately using the ps.lib.io.fileio.FileIO() function
- read() is a more fundamental IO method than the read csv() method and the file handle needs to be closed

In [1]:
import pandas as pd
import pysal as ps

housingdf = pd.read_csv('psam_h17.csv', dtype={'PUMA':str})
shp_path = 'tl_2018_17_puma10.shp'
f = ps.lib.io.fileio.FileIO(shp_path)
all_polygons = f.read()
f.close()

### Examining our spatial features
- The result of reading the shape file is a list of polygons

In [2]:
type(all_polygons)

list

In [3]:
type(all_polygons[0])

pysal.lib.cg.shapes.Polygon

In [4]:
all_polygons[0]

In [5]:
all_polygons[0].vertices

[(-87.721436, 41.734862),
 (-87.721417, 41.734863),
 (-87.72134799999999, 41.734863999999995),
 (-87.72113, 41.734866),
 (-87.721054, 41.734868),
 (-87.72064499999999, 41.734874),
 (-87.71941799999999, 41.734895),
 (-87.71901, 41.734902),
 (-87.718522, 41.734911),
 (-87.717168, 41.734938),
 (-87.71705999999999, 41.734939),
 (-87.716573, 41.734944999999996),
 (-87.71608599999999, 41.73495),
 (-87.715671, 41.734955),
 (-87.714629, 41.734984999999995),
 (-87.71457199999999, 41.734987),
 (-87.71414299999999, 41.734992999999996),
 (-87.713709, 41.734998),
 (-87.71300699999999, 41.735008),
 (-87.71240999999999, 41.73502),
 (-87.711978, 41.735029),
 (-87.711923, 41.735029),
 (-87.71176, 41.735032),
 (-87.71170599999999, 41.735034),
 (-87.711658, 41.735034999999996),
 (-87.71162199999999, 41.735036),
 (-87.710782, 41.735051999999996),
 (-87.709862, 41.735071),
 (-87.709245, 41.735079999999996),
 (-87.708012, 41.735099),
 (-87.70783999999999, 41.735102),
 (-87.707089, 41.735115),
 (-87.70609499999999, 41.735132),
 (-87.704411, 41.735161999999995),
 (-87.70311699999999, 41.735186),
 (-87.702302, 41.735202),
 (-87.702124, 41.735203),
 (-87.701906, 41.735205),
 (-87.70125499999999, 41.735212),
 (-87.701038, 41.735215),
 (-87.70079, 41.735217),
 (-87.700245, 41.735223999999995),
 (-87.70004899999999, 41.735226999999995),
 (-87.69980199999999, 41.735233),
 (-87.699551, 41.735237999999995),
 (-87.698798, 41.735253),
 (-87.69854699999999, 41.735257999999995),
 (-87.698301, 41.735261),
 (-87.697563, 41.735273),
 (-87.697318, 41.735276999999996),
 (-87.697109, 41.735279999999996),
 (-87.696899, 41.735282999999995),
 (-87.696269, 41.735293),
 (-87.69606, 41.735296999999996),
 (-87.69581, 41.735301),
 (-87.695062, 41.735313999999995),
 (-87.694813, 41.735319),
 (-87.694655, 41.735322),
 (-87.694439, 41.735324999999996),
 (-87.69379099999999, 41.735338),
 (-87.693576, 41.735341999999996),
 (-87.69336299999999, 41.735344999999995),
 (-87.69332899999999, 41.735344999999995),
 (-87.692591, 41.735358),
 (-87.692345, 41.735363),
 (-87.69224799999999, 41.735365),
 (-87.69202299999999, 41.735368),
 (-87.69134799999999, 41.735378999999995),
 (-87.691124, 41.735383),
 (-87.690879, 41.735385),
 (-87.690364, 41.735392),
 (-87.690147, 41.735396),
 (-87.689903, 41.735402),
 (-87.689854, 41.735402),
 (-87.689709, 41.735406),
 (-87.689661, 41.735406999999995),
 (-87.689499, 41.735409),
 (-87.689013, 41.735417),
 (-87.688852, 41.73542),
 (-87.688729, 41.735420999999995),
 (-87.688362, 41.735426),
 (-87.68824, 41.735428999999996),
 (-87.688092, 41.735431),
 (-87.687651, 41.735439),
 (-87.687505, 41.735442),
 (-87.687482, 41.735442),
 (-87.687417, 41.735443),
 (-87.687395, 41.735444),
 (-87.687354, 41.735444),
 (-87.68641799999999, 41.735459),
 (-87.685109, 41.735482),
 (-87.68348999999999, 41.735507999999996),
 (-87.682514, 41.735524999999996),
 (-87.682487, 41.734725),
 (-87.682485, 41.734657),
 (-87.682468, 41.73393),
 (-87.682417, 41.732327),
 (-87.682392, 41.731528),
 (-87.68238199999999, 41.731232999999996),
 (-87.682355, 41.730351999999996),
 (-87.682346, 41.730058),
 (-87.682335, 41.729693),
 (-87.68230199999999, 41.7286),
 (-87.68229099999999, 41.728235999999995),
 (-87.682273, 41.727644),
 (-87.682234, 41.726265),
 (-87.682222, 41.725868999999996),
 (-87.682206, 41.725277999999996),
 (-87.68220000000001, 41.725124),
 (-87.68218499999999, 41.724664999999995),
 (-87.682181, 41.724512),
 (-87.682178, 41.724418),
 (-87.682125, 41.722764999999995),
 (-87.68209499999999, 41.721829),
 (-87.68209, 41.721655999999996),
 (-87.682088, 41.721605),
 (-87.68208299999999, 41.721452),
 (-87.682082, 41.721401),
 (-87.68206699999999, 41.72094),
 (-87.682011, 41.719111),
 (-87.682, 41.718745),
 (-87.68198, 41.718067),
 (-87.68196999999999, 41.717649),
 (-87.681962, 41.717284),
 (-87.681953, 41.716927999999996),
 (-87.68195, 41.716772999999996),
 (-87.681918, 41.715862),
 (-87.68191399999999, 41.715726),
 (-87.681907, 41.715506999999995),
 (-87.681894, 41.71514),
 (-87.681855, 41.714039),
 (-87.681843, 41.713671999999995),
 (-87.682098, 41.713668),
 (-87.682332, 41.713665999999996),
 (-87.68251099999999, 41.713667),
 (-87.682649, 41.713668),
 (-87.682867, 41.713664),
 (-87.683123, 41.713660999999995),
 (-87.68324899999999, 41.713657),
 (-87.68336599999999, 41.713656),
 (-87.683725, 41.713653),
 (-87.684095, 41.713649),
 (-87.684339, 41.713646999999995),
 (-87.684649, 41.713643),
 (-87.68477399999999, 41.713642),
 (-87.684894, 41.713637),
 (-87.68495399999999, 41.713637999999996),
 (-87.68557799999999, 41.713631),
 (-87.685889, 41.713628),
 (-87.686072, 41.713626),
 (-87.68662599999999, 41.713620999999996),
 (-87.686753, 41.71362),
 (-87.686804, 41.713619),
 (-87.687045, 41.713615999999995),
 (-87.68776799999999, 41.713609),
 (-87.68800999999999, 41.713608),
 (-87.68825799999999, 41.713604),
 (-87.689002, 41.713594),
 (-87.689251, 41.713592),
 (-87.68949599999999, 41.713589999999996),
 (-87.689889, 41.713589),
 (-87.69023299999999, 41.713583),
 (-87.690479, 41.71358),
 (-87.69072899999999, 41.713577),
 (-87.691102, 41.713574),
 (-87.691481, 41.713569),
 (-87.691732, 41.713566),
 (-87.691727, 41.713384),
 (-87.69171899999999, 41.713091),
 (-87.691709, 41.712838),
 (-87.69170199999999, 41.712657),
 (-87.691696, 41.712475),
 (-87.691679, 41.711929),
 (-87.69167399999999, 41.711748),
 (-87.69166799999999, 41.711565),
 (-87.691651, 41.711019),
 (-87.69164599999999, 41.710837),
 (-87.69163999999999, 41.710654999999996),
 (-87.691622, 41.71011),
 (-87.691616, 41.709928999999995),
 (-87.69161, 41.709745999999996),
 (-87.691592, 41.7092),
 (-87.691587, 41.709018),
 (-87.69158, 41.708836),
 (-87.69156199999999, 41.70829),
 (-87.69155599999999, 41.708109),
 (-87.69154999999999, 41.70793),
 (-87.69153299999999, 41.707395999999996),
 (-87.69153, 41.707282),
 (-87.691535, 41.707218),
 (-87.691611, 41.707204),
 (-87.692022, 41.707197),
 (-87.692064, 41.707197),
 (-87.69349, 41.70718),
 (-87.69398, 41.707175),
 (-87.694474, 41.707169),
 (-87.69556399999999, 41.707156999999995),
 (-87.695956, 41.707152),
 (-87.696229, 41.707149),
 (-87.696266, 41.707149),
 (-87.696451, 41.707150999999996),
 (-87.69668, 41.707136),
 (-87.697287, 41.707132),
 (-87.69843999999999, 41.707114),
 (-87.701371, 41.707085),
 (-87.701363, 41.706936999999996),
 (-87.701334, 41.706373),
 (-87.701325, 41.706185999999995),
 (-87.70156899999999, 41.706184),
 (-87.70194099999999, 41.706181),
 (-87.70230099999999, 41.706176),
 (-87.702545, 41.706174),
 (-87.702794, 41.70617),
 (-87.703149, 41.706165999999996),
 (-87.703544, 41.706161),
 (-87.703794, 41.706157999999995),
 (-87.704042, 41.706154),
 (-87.704461, 41.706148999999996),
 (-87.70478899999999, 41.706143999999995),
 (-87.705038, 41.706140999999995),
 (-87.70527899999999, 41.706137),
 (-87.70566099999999, 41.706132),
 (-87.70600499999999, 41.706126999999995),
 (-87.70624699999999, 41.706123999999996),
 (-87.70648899999999, 41.70612),
 (-87.706846, 41.706115),
 (-87.707218, 41.706109),
 (-87.707461, 41.706106),
 (-87.707712, 41.706102),
 (-87.708467, 41.706089999999996),
 (-87.708719, 41.706087),
 (-87.70891, 41.706084),
 (-87.70896599999999, 41.706083),
 (-87.70971, 41.706083),
 (-87.709959, 41.706083),
 (-87.710191, 41.706081999999995),
 (-87.71088999999999, 41.706078999999995),
 (-87.711123, 41.706078999999995),
 (-87.711134, 41.706430999999995),
 (-87.71117, 41.707488),
 (-87.71117699999999, 41.707705999999995),
 (-87.711182, 41.707840999999995),
 (-87.71118299999999, 41.707871999999995),
 (-87.711186, 41.707972999999996),
 (-87.711193, 41.708206),
 (-87.711227, 41.709303999999996),
 (-87.71123899999999, 41.709669999999996),
 (-87.71125099999999, 41.710034),
 (-87.711283, 41.710995),
 (-87.711287, 41.711126),
 (-87.711299, 41.711490999999995),
 (-87.711469, 41.711498999999996),
 (-87.711979, 41.711524),
 (-87.71215, 41.711532999999996),
 (-87.71256199999999, 41.71151),
 (-87.712578, 41.713296),
 (-87.712822, 41.713291999999996),
 (-87.713557, 41.713280999999995),
 (-87.713802, 41.713277999999995),
 (-87.71404299999999, 41.713274),
 (-87.71441, 41.713269),
 (-87.71476899999999, 41.713263),
 (-87.71501099999999, 41.71326),
 (-87.715257, 41.713256),
 (-87.715631, 41.713251),
 (-87.71599499999999, 41.713245),
 (-87.716242, 41.713242),
 (-87.71648599999999, 41.713238),
 (-87.71685099999999, 41.713234),
 (-87.717218, 41.713228),
 (-87.717463, 41.713225),
 (-87.71770699999999, 41.713221),
 (-87.718079, 41.713215999999996),
 (-87.718442, 41.71321),
 (-87.718687, 41.713207),
 (-87.718931, 41.713203),
 (-87.719662, 41.713190999999995),
 (-87.71990699999999, 41.713187999999995),
 (-87.72014999999999, 41.713184),
 (-87.720486, 41.71318),
 (-87.72088099999999, 41.713173),
 (-87.721125, 41.71317),
 (-87.72112, 41.712984999999996),
 (-87.72110599999999, 41.712433),
 (-87.721102, 41.712249),
 (-87.721099, 41.712069),
 (-87.721092, 41.711529),
 (-87.72108999999999, 41.711349),
 (-87.721079, 41.710983),
 (-87.721046, 41.709888),
 (-87.721036, 41.709523),
 (-87.721034, 41.709458),
 (-87.721026, 41.709243),
 (-87.72100499999999, 41.708597999999995),
 (-87.720998, 41.708383999999995),
 (-87.72099299999999, 41.708248999999995),
 (-87.720981, 41.707847),
 (-87.720978, 41.707713),
 (-87.72097099999999, 41.707519),
 (-87.720959, 41.70719),
 (-87.72092599999999, 41.706205999999995),
 (-87.72091499999999, 41.705878),
 (-87.720908, 41.705684),
 (-87.720828, 41.704043),
 (-87.720794, 41.703201),
 (-87.72079, 41.703095999999995),
 (-87.720759, 41.702225),
 (-87.72075199999999, 41.702042),
 (-87.720744, 41.701811),
 (-87.720731, 41.701493),
 (-87.72072399999999, 41.701311),
 (-87.72071799999999, 41.701127),
 (-87.720711, 41.700904),
 (-87.720697, 41.700578),
 (-87.72068999999999, 41.700396),
 (-87.720683, 41.700282),
 (-87.720682, 41.700213),
 (-87.720675, 41.699666),
 (-87.72067299999999, 41.699484),
 (-87.720666, 41.6993),
 (-87.72064499999999, 41.698749),
 (-87.72063899999999, 41.698566),
 (-87.720615, 41.698042),
 (-87.72058899999999, 41.697441),
 (-87.720564, 41.697054),
 (-87.720547, 41.696709),
 (-87.720539, 41.696554),
 (-87.720536, 41.696473),
 (-87.720524, 41.696099),
 (-87.720519, 41.695949999999996),
 (-87.720513, 41.695809),
 (-87.72052699999999, 41.695747),
 (-87.72053, 41.695730999999995),
 (-87.720548, 41.695662),
 (-87.72052699999999, 41.695074),
 (-87.72052, 41.694854),
 (-87.720505, 41.694493),
 (-87.720463, 41.69341),
 (-87.720461, 41.693349),
 (-87.720445, 41.693244),
 (-87.720417, 41.693053),
 (-87.720401, 41.69294),
 (-87.72039199999999, 41.692696999999995),
 (-87.72038599999999, 41.692535),
 (-87.720371, 41.692166),
 (-87.720337, 41.69172),
 (-87.720332, 41.691627),
 (-87.720317, 41.691271),
 (-87.720435, 41.691303),
 (-87.720537, 41.691316),
 (-87.72117, 41.691308),
 (-87.721684, 41.691303),
 (-87.72299, 41.69128),
 (-87.723747, 41.691265),
 (-87.723885, 41.691263),
 (-87.724606, 41.691252),
 (-87.72463499999999, 41.691251),
 (-87.724722, 41.691249),
 (-87.724752, 41.691249),
 (-87.72496, 41.691244),
 (-87.725207, 41.69124),
 (-87.725585, 41.691237),
 (-87.725714, 41.691237),
 (-87.725794, 41.691234),
 (-87.72594199999999, 41.691227),
 (-87.72648099999999, 41.691216999999995),
 (-87.726649, 41.691213),
 (-87.72921699999999, 41.691158),
 (-87.73007299999999, 41.691140999999995),
 (-87.730308, 41.691137),
 (-87.731015, 41.691125),
 (-87.731251, 41.691122),
 (-87.731494, 41.691117),
 (-87.73222299999999, 41.691103999999996),
 (-87.732467, 41.6911),
 (-87.732951, 41.691089999999996),
 (-87.73440599999999, 41.691063),
 (-87.734529, 41.691061),
 (-87.734892, 41.691055999999996),
 (-87.735377, 41.691047),
 (-87.736285, 41.691030999999995),
 (-87.73683299999999, 41.691016),
 (-87.73686599999999, 41.691016),
 (-87.737184, 41.690996999999996),
 (-87.737318, 41.690982),
 (-87.73755799999999, 41.690951),
 (-87.738284, 41.69094),
 (-87.73852699999999, 41.690937),
 (-87.738767, 41.690933),
 (-87.739299, 41.690926999999995),
 (-87.73948899999999, 41.690911),
 (-87.73973, 41.690891),
 (-87.739729, 41.690878999999995),
 (-87.73972599999999, 41.690844),
 (-87.73972599999999, 41.690833),
 (-87.739716, 41.690704),
 (-87.739679, 41.689392),
 (-87.73967499999999, 41.689215),
 (-87.73966399999999, 41.688998),
 (-87.739592, 41.687204),
 (-87.739521, 41.685358),
 (-87.739509, 41.685072),
 (-87.739449, 41.683631999999996),
 (-87.73920199999999, 41.683636),
 (-87.738462, 41.68365),
 (-87.738429, 41.683651),
 (-87.738216, 41.683651),
 (-87.73810399999999, 41.683651),
 (-87.738045, 41.683651999999995),
 (-87.737526, 41.683667),
 (-87.737364, 41.683668),
 (-87.736734, 41.683678),
 (-87.73608899999999, 41.683688),
 (-87.735474, 41.683698),
 (-87.734324, 41.68372),
 (-87.732264, 41.683758999999995),
 (-87.731904, 41.683766),
 (-87.731177, 41.683779),
 (-87.731105, 41.683775),
 (-87.73098999999999, 41.683779),
 (-87.730794, 41.683786),
 (-87.730721, 41.683786999999995),
 (-87.729914, 41.683800999999995),
 (-87.72964499999999, 41.683806),
 (-87.729377, 41.683809),
 (-87.72857499999999, 41.683822),
 (-87.728308, 41.683827),
 (-87.728106, 41.68383),
 (-87.727992, 41.683831),
 (-87.727046, 41.683847),
 (-87.726731, 41.683853),
 (-87.72636399999999, 41.683859),
 (-87.725574, 41.683873),
 (-87.725263, 41.683876999999995),
 (-87.724896, 41.683883),
 (-87.724818, 41.683883),
 (-87.724584, 41.683887),
 (-87.724507, 41.683889),
 (-87.724342, 41.683890999999996),
 (-87.72384699999999, 41.683899),
 (-87.723683, 41.683901999999996),
 (-87.72344, 41.683907999999995),
 (-87.72305399999999, 41.683918),
 (-87.72271099999999, 41.683923),
 (-87.72246799999999, 41.683927),
 (-87.72222599999999, 41.68393),
 (-87.721553, 41.683941),
 (-87.72150099999999, 41.68394),
 (-87.72133099999999, 41.683938999999995),
 (-87.72126, 41.683941999999995),
 (-87.721021, 41.683949999999996),
 (-87.720963, 41.683952),
 (-87.720304, 41.683963),
 (-87.72006499999999, 41.683966999999996),
 (-87.719881, 41.683969),
 (-87.719329, 41.683977),
 (-87.719146, 41.68398),
 (-87.719006, 41.683982),
 (-87.71891099999999, 41.683983),
 (-87.718836, 41.683983999999995),
 (-87.71790999999999, 41.683997999999995),
 (-87.717601, 41.684003),
 (-87.717111, 41.68401),
 (-87.715643, 41.684034),
 (-87.715154, 41.684042),
 (-87.71467, 41.684048),
 (-87.713218, 41.68407),
 (-87.712735, 41.684076999999995),
 (-87.712437, 41.68408),
 (-87.71212, 41.684084999999996),
 (-87.711546, 41.684092),
 (-87.71151599999999, 41.684093),
 (-87.71149299999999, 41.683644),
 (-87.711478, 41.683192999999996),
 (-87.711455, 41.682727),
 (-87.71141999999999, 41.682272999999995),
 (-87.711355, 41.682272999999995),
 (-87.711325, 41.681954),
 (-87.711326, 41.681808),
 (-87.71159899999999, 41.681802999999995),
 (-87.711576, 41.681356),
 (-87.71139, 41.681267999999996),
 (-87.711376, 41.680906),
 (-87.71136, 41.680437999999995),
 (-87.711221, 41.680442),
 (-87.711113, 41.680443),
 (-87.710374, 41.680451),
 (-87.710315, 41.680451999999995),
 (-87.71019, 41.680464),
 (-87.71012999999999, 41.680479),
 (-87.71001199999999, 41.680527999999995),
 (-87.709972, 41.680543),
 (-87.709931, 41.680547999999995),
 (-87.70965699999999, 41.680551),
 (-87.708856, 41.680561),
 (-87.708798, 41.680561),
 (-87.7082, 41.680561),
 (-87.707715, 41.680561999999995),
 (-87.707573, 41.680564),
 (-87.707324, 41.680566),
 (-87.707229, 41.680558999999995),
 (-87.707146, 41.680552999999996),
 (-87.706094, 41.680561),
 (-87.705771, 41.680568),
 (-87.70528499999999, 41.680579),
 (-87.70527899999999, 41.680685),
 (-87.705281, 41.680752),
 (-87.705291, 41.681019),
 (-87.70530000000001, 41.681273),
 (-87.70530699999999, 41.681447),
 (-87.705314, 41.681629),
 (-87.705327, 41.681909),
 (-87.705332, 41.682046),
 (-87.705337, 41.682178),
 (-87.705339, 41.682227),
 (-87.705344, 41.682362),
 (-87.70534699999999, 41.682455999999995),
 (-87.705361, 41.682826),
 (-87.705366, 41.682955),
 (-87.705378, 41.683277),
 (-87.70538499999999, 41.683459),
 (-87.70539699999999, 41.683738999999996),
 (-87.70540799999999, 41.684005),
 (-87.705417, 41.684187),
 (-87.70492899999999, 41.684194999999995),
 (-87.70487, 41.684196),
 (-87.703468, 41.684217),
 (-87.702981, 41.684225),
 (-87.702731, 41.684228),
 (-87.701985, 41.684239999999996),
 (-87.701736, 41.684244),
 (-87.701499, 41.684247),
 (-87.700789, 41.684259),
 (-87.700553, 41.684263),
 (-87.70056199999999, 41.684532999999995),
 (-87.700592, 41.685345999999996),
 (-87.70060199999999, 41.685617),
 (-87.700606, 41.685719999999996),
 (-87.70061899999999, 41.686029999999995),
 (-87.70062399999999, 41.686133999999996),
 (-87.700378, 41.686136999999995),
 (-87.700019, 41.686143),
 (-87.699643, 41.686146),
 (-87.699398, 41.686149),
 (-87.69940299999999, 41.686223),
 (-87.699411, 41.686329),
 (-87.699415, 41.686447),
 (-87.699418, 41.686522),
 (-87.699424, 41.686698),
 (-87.699445, 41.687227),
 (-87.699452, 41.687404),
 (-87.699456, 41.687509),
 (-87.699468, 41.687827),
 (-87.699473, 41.687933),
 (-87.69923, 41.687936),
 (-87.698869, 41.687942),
 (-87.69850199999999, 41.687947),
 (-87.698436, 41.687948),
 (-87.69825999999999, 41.687947),
 (-87.698026, 41.687945),
 (-87.697986, 41.687945),
 (-87.697662, 41.687951),
 (-87.697426, 41.687956),
 (-87.69732499999999, 41.687959),
 (-87.697092, 41.687968999999995),
 (-87.696991, 41.687971999999995),
 (-87.696781, 41.687981),
 (-87.696688, 41.687982),
 (-87.696606, 41.687984),
 (-87.69658799999999, 41.687987),
 (-87.69650999999999, 41.687999),
 (-87.69644699999999, 41.688007999999996),
 (-87.69642499999999, 41.688012),
 (-87.69624499999999, 41.688023),
 (-87.696148, 41.688033),
 (-87.695717, 41.688032),
 (-87.69572, 41.688151),
 (-87.69575499999999, 41.688845),
 (-87.69586, 41.69093),
 (-87.695895, 41.691624999999995),
 (-87.695906, 41.691807),
 (-87.69594099999999, 41.692353999999995),
 (-87.695953, 41.692537),
 (-87.69597499999999, 41.693090999999995),
 (-87.696043, 41.694755),
 (-87.696066, 41.69531),
 (-87.696073, 41.695679),
 (-87.696095, 41.696788),
 (-87.696103, 41.697157999999995),
 (-87.696112, 41.697517999999995),
 (-87.696142, 41.698599),
 (-87.696152, 41.69896),
 (-87.695161, 41.698964),
 (-87.69219, 41.69898),
 (-87.69120000000001, 41.698986),
 (-87.691187, 41.698620999999996),
 (-87.691148, 41.697525999999996),
 (-87.691136, 41.697162),
 (-87.691124, 41.696797),
 (-87.691088, 41.695704),
 (-87.69107699999999, 41.69534),
 (-87.691065, 41.694972),
 (-87.691045, 41.694303),
 (-87.691026, 41.693871),
 (-87.69101099999999, 41.693504),
 (-87.69099899999999, 41.693242),
 (-87.690995, 41.69314),
 (-87.690974, 41.69244),
 (-87.690967, 41.692284),
 (-87.690963, 41.692167),
 (-87.690958, 41.692051),
 (-87.69094299999999, 41.691688),
 (-87.690933, 41.691348999999995),
 (-87.69090299999999, 41.690334),
 (-87.690894, 41.689996),
 (-87.69089, 41.689625),
 (-87.690878, 41.688514999999995),
 (-87.690874, 41.688145),
 (-87.690863, 41.687396),
 (-87.690833, 41.68515),
 (-87.690823, 41.684402),
 (-87.690561, 41.684405),
 (-87.689779, 41.684416),
 (-87.68951799999999, 41.684419999999996),
 (-87.689272, 41.684422999999995),
 (-87.6889, 41.684429),
 (-87.688537, 41.684433999999996),
 (-87.68829199999999, 41.684439),
 (-87.688046, 41.684442),
 (-87.687308, 41.684453999999995),
 (-87.687063, 41.684459),
 (-87.68684999999999, 41.684461),
 (-87.68621399999999, 41.68447),
 (-87.686002, 41.684473),
 (-87.685974, 41.684473),
 (-87.685891, 41.684474),
 (-87.685864, 41.684475),
 (-87.685847, 41.684293),
 (-87.68582599999999, 41.684051),
 (-87.685814, 41.683748),
 (-87.685808, 41.683566),
 (-87.685801, 41.683384),
 (-87.68578099999999, 41.68284),
 (-87.68577499999999, 41.682659),
 (-87.68576999999999, 41.682477),
 (-87.68575799999999, 41.681931),
 (-87.685754, 41.681748999999996),
 (-87.685746, 41.681567),
 (-87.68572499999999, 41.681022999999996),
 (-87.685718, 41.680842),
 (-87.685678, 41.67993),
 (-87.68566299999999, 41.679491),
 (-87.685699, 41.679030999999995),
 (-87.68576, 41.678619),
 (-87.685847, 41.678371999999996),
 (-87.68592699999999, 41.678134),
 (-87.68601199999999, 41.677946999999996),
 (-87.686275, 41.677389999999995),
 (-87.686363, 41.677205),

The polygon vertices are the longitude and latitude

PySAL Shapes include a substantial number of precomputed attributes and efficient methods

In [6]:
all_polygons[0].centroid

(-87.73227916862234, 41.68628900126081)

In [7]:
all_polygons[0].perimeter

0.7424176724174986

In [8]:
all_polygons[0].area

0.010349874158494149

In [9]:
ps.lib.cg.get_shared_segments(all_polygons[0], all_polygons[14])

[<pysal.lib.cg.shapes.LineSegment at 0x7fb1da274eb8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1da274dd8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1da274d30>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1da274cc0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7048>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7080>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed70b8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed70f0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7128>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7160>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7198>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed71d0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7208>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7240>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7278>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed72b0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed72e8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7320>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7358>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7390>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed73c8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7400>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7438>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7470>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed74a8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed74e0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7518>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7550>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7588>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed75c0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed75f8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7630>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7668>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed76a0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed76d8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7710>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7748>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7780>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed77b8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed77f0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7828>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7860>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7898>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed78d0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7908>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7940>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7978>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed79b0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed79e8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7a20>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7a58>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7a90>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7ac8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7b00>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7b38>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7b70>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7ba8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7be0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7c18>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7c50>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7c88>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7cc0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7cf8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7d30>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7d68>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7da0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7dd8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7e10>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7e48>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7e80>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7eb8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7ef0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7f28>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7f60>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7f98>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed7fd0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9048>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9080>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed90b8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed90f0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9128>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9160>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9198>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed91d0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9208>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9240>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9278>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed92b0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed92e8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9320>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9358>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9390>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed93c8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9400>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9438>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9470>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed94a8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed94e0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9518>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9550>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9588>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed95c0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed95f8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9630>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9668>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed96a0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed96d8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9710>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9748>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9780>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed97b8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed97f0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9828>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9860>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9898>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed98d0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9908>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9940>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9978>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed99b0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed99e8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9a20>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9a58>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9a90>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9ac8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9b00>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9b38>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9b70>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9ba8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9be0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9c18>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9c50>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9c88>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9cc0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9cf8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9d30>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9d68>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9da0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9dd8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9e10>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9e48>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9e80>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9eb8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9ef0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9f28>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9f60>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9f98>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ed9fd0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd048>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd080>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd0b8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd0f0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd128>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd160>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd198>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd1d0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd208>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd240>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd278>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd2b0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd2e8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd320>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd358>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd390>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd3c8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd400>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd438>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd470>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd4a8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd4e0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd518>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd550>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd588>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd5c0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd5f8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd630>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd668>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd6a0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd6d8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd710>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd748>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd780>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd7b8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd7f0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd828>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd860>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd898>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd8d0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd908>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd940>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd978>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd9b0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edd9e8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edda20>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edda58>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edda90>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddac8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddb00>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddb38>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddb70>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddba8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddbe0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddc18>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddc50>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddc88>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddcc0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddcf8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddd30>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddd68>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddda0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edddd8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edde10>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edde48>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9edde80>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddeb8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddef0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddf28>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddf60>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddf98>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9eddfd0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1048>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1080>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee10b8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee10f0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1128>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1160>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1198>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee11d0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1208>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1240>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1278>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee12b0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee12e8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1320>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1358>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1390>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee13c8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1400>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1438>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1470>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee14a8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee14e0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1518>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1550>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1588>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee15c0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee15f8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1630>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1668>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee16a0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee16d8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1710>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1748>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1780>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee17b8>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee17f0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1828>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1860>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1898>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee18d0>,
 <pysal.lib.cg.shapes.LineSegment at 0x7fb1d9ee1908>]

The computed segments are the shared boundary of the two polygons.

### Where is the data associated with the shapes?
- In order to capture the attributes associated with the shapes themselves, we will need to read the associated .dbf file
- There are two reasons to do this:
    - First, the regions probably have some interesting additional data from the census
    - Second, we don’t have labels for these shapes so we can’t link them to the housingdf!

In [11]:
dfpoly = pd.DataFrame(all_polygons,columns=['polygon'])
dbf_path = 'tl_2018_17_puma10.dbf'
f2 = ps.lib.io.fileio.FileIO(dbf_path)
dbheader = f2.header
dbfile = f2.read()
f2.close()
pd.DataFrame(dbfile, columns=dbheader).head()

,STATEFP10,PUMACE10,GEOID10,NAMELSAD10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10
0,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725
1,17,03107,1703107,"Will County (Northeast)--Frankfort, Homer & Ne...",G6120,S,243596923,478565,+41.5528956,-087.9168232
2,17,03700,1703700,Kendall & Grundy Counties PUMA,G6120,S,1912412909,37262592,+41.4200983,-088.4339373
3,17,02000,1702000,McLean County PUMA,G6120,S,3064559693,7853695,+40.4945594,-088.8445391
4,17,01602,1701602,"Menard, Logan, De Witt, Piatt, Moultrie, Shelb...",G6120,S,9254202416,88234698,+39.7699432,-089.2258108

### Producing a complete data set
- The coordinates of the centroid of the first elements seem to agree
- Let’s try and combine them by pd.concat and then join to the csv file

In [14]:
geo_df1 = pd.concat([pd.DataFrame(dbfile, columns=dbheader),dfpoly],axis=1)
geo_df1.head()
pd.merge(geo_df1, housingdf,how='inner',left_on=['PUMACE10'],right_on=['PUMA'])

,STATEFP10,PUMACE10,GEOID10,NAMELSAD10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,...,WGTP71,WGTP72,WGTP73,WGTP74,WGTP75,WGTP76,WGTP77,WGTP78,WGTP79,WGTP80
0,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,25,42,37,19,25,25,19,48,31,20
1,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,10,50,11,38,42,11,32,12,79,42
2,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,43,9,6,27,25,25,25,42,9,41
3,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,17,32,26,6,5,28,17,5,31,17
4,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,16,17,5,15,4,5,28,28,16,16
5,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,15,16,15,27,17,5,15,27,27,14
6,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,10,50,36,31,34,51,29,32,33,53
7,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,4,17,5,14,15,4,16,5,30,15
8,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,27,27,4,16,4,15,17,5,15,15
9,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,53,18,49,47,84,88,16,16,91,86
10,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,51,35,9,54,40,64,36,11,47,9
11,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,16,4,15,4,4,25,15,26,16,16
12,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,19,10,11,18,10,3,4,3,10,3
13,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,4,8,9,9,9,9,15,16,17,15
14,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,51,9,25,13,37,47,35,70,16,11
15,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,4,30,15,27,16,14,16,24,29,5
16,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,7,48,51,31,34,7,8,52,31,45
17,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,100,63,55,16,17,101,63,72,64,101
18,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,13,13,3,11,21,3,12,4,13,3
19,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,27,17,4,5,16,15,5,28,17,15
20,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,124,214,142,33,102,243,204,112,122,134
21,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,12,15,13,4,12,20,3,15,3,21
22,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,21,14,12,18,13,14,12,22,4,13
23,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,4,25,14,25,26,14,15,14,14,3
24,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,5,18,4,6,19,15,18,18,7,7
25,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,13,4,23,14,13,3,14,3,5,13
26,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,0,0,0,0,0,0,0,0,0,0
27,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,4,16,17,4,16,29,5,5,26,5
28,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,0,0,0,0,0,0,0,0,0,0
29,17,03411,1703411,Cook County (South Central)--Worth & Calumet T...,G6120,S,94129155,1576803,+41.7313634,-087.7167725,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292898,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,20,39,18,20,5,27,7,5,19,20
292899,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,6,26,26,27,38,25,8,25,8,23
292900,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,17,14,5,5,28,30,5,18,29,16
292901,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,7,22,26,8,33,10,43,48,32,24
292902,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,5,5,16,29,5,20,21,17,18,18
292903,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,20,35,7,22,37,43,19,23,24,21
292904,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,38,9,9,32,27,51,37,30,26,33
292905,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,43,75,44,68,80,13,36,15,43,37
292906,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,29,23,22,6,9,8,24,48,24,7
292907,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,31,32,10,32,31,33,52,31,33,9
292908,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,21,14,13,17,20,12,11,19,3,12
292909,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,4,19,19,4,16,16,5,19,15,17
292910,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,21,6,4,5,4,22,11,14,3,4
292911,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,30,44,20,19,15,20,20,7,21,29
292912,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,22,15,12,21,23,22,20,12,23,15
292913,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,29,33,24,26,19,6,9,23,28,23
292914,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,38,20,22,7,8,42,38,6,22,26
292915,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,9,12,12,12,8,2,7,11,6,13
292916,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292917,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292918,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292919,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292920,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292921,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292922,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292923,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292924,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292925,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292926,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0
292927,17,03526,1703526,"Chicago City (Southwest)--Brighton Park, New C...",G6120,S,36103882,184999,+41.8186679,-087.6734421,...,0,0,0,0,0,0,0,0,0,0

### Is this enough to get things done?
- This is a useful structure (especially for doing complex spatial statistics)
- We can automate complex problems for filtering and producing attributes derived from spatial features
- We have two problems that remain unsolved by this: projection and fast spatial indexing

In [15]:
geo_df1['computed_area']=geo_df1['polygon'].map(lambda x: x.area)
geo_df1['total_listed_area']=geo_df1.ALAND10+geo_df1.AWATER10

### Problems

1) Following the slides, assemble a dataframe from the csv, dbf, and shp files name it geo df1

2) 2 Use the code from the “Is this enough...” slide to compute the area from the polygons and the area listed in the dbf